[2022-01-31 14:11:45,837] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag_test.local_to_gcs_task scheduled__2019-07-01T00:00:00+00:00 [queued]>
[2022-01-31 14:11:46,587] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag_test.local_to_gcs_task scheduled__2019-07-01T00:00:00+00:00 [queued]>
[2022-01-31 14:11:46,610] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-31 14:11:46,614] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-31 14:11:46,616] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-31 14:11:47,123] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-07-01 00:00:00+00:00
[2022-01-31 14:11:47,231] {standard_task_runner.py:52} INFO - Started process 4878 to run task
[2022-01-31 14:11:47,322] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag_test', 'local_to_gcs_task', 'scheduled__2019-07-01T00:00:00+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmppde8_8qn', '--error-file', '/tmp/tmpia2_wc2d']
[2022-01-31 14:11:47,344] {standard_task_runner.py:77} INFO - Job 263: Subtask local_to_gcs_task
[2022-01-31 14:11:48,512] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag_test.local_to_gcs_task scheduled__2019-07-01T00:00:00+00:00 [running]> on host e72d6c5f15dc
[2022-01-31 14:11:49,589] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-31 14:11:49,923] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag_test
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-07-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-07-01T00:00:00+00:00
[2022-01-31 14:12:38,629] {python.py:175} INFO - Done. Returned value was: None
[2022-01-31 14:12:39,530] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag_test, task_id=local_to_gcs_task, execution_date=20190701T000000, start_date=20220131T141145, end_date=20220131T141239
[2022-01-31 14:12:40,251] {local_task_job.py:212} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-01-31 14:12:40,668] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 4878. PIDs of all processes in the group: [4878]
[2022-01-31 14:12:40,700] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 4878
[2022-01-31 14:12:41,097] {process_utils.py:70} INFO - Process psutil.Process(pid=4878, status='terminated', exitcode=0, started='14:11:46') (4878) terminated with exit code 0
